-- 테이블 생성 쿼리 정리

-- IT Assets--------------------------------------------------------------------------
-- ITASSETS
CREATE TABLE ITASSETS (
  ASSETS_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NUM INT,
  ASSETS_NAME VARCHAR(255),
  ASSETS_DETAIL_NAME VARCHAR(45),
  ASSETS_STATUS VARCHAR(30),
  SPEC_NUM VARCHAR(50),
  username VARCHAR(45),
  ADD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  RENT_DATE DATETIME
);
-- PCSPEC
CREATE TABLE PCSPEC (
  SPEC_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SPEC_CPU VARCHAR(30),
  SPEC_RAM VARCHAR(30),
  SPEC_MAINBOARD VARCHAR(30),
  SPEC_POWER VARCHAR(30),
  SPEC_GPU VARCHAR(30),
  SPEC_HDD VARCHAR(30),
  SPEC_SSD VARCHAR(30),
  SPEC_OPS VARCHAR(50),
  SPEC_MFG VARCHAR(50),
  SPEC_SERIEL VARCHAR(45),
  SPEC_PURCHASE_DATE DATE,
  SPEC_WARRANTY DATE
);
-- SWSPEC
CREATE TABLE SWSPEC (
  SPEC_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SW_MFG VARCHAR(30),
  SW_SPEC_SERIEL VARCHAR(45),
  SW_SPEC_WARRANTY DATE,
  SW_PURCHASE_DATE DATE,
  SW_PRICE VARCHAR(45)
);
-- SERVERSPEC
CREATE TABLE SERVERSPEC (
  SPEC_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SERVER_MFG VARCHAR(30),
  SERVER_SPEC_WARRANTY DATE,
  SERVER_CAPA VARCHAR(30),
  SERVER_PRICE VARCHAR(45),
  SERVER_PURCHASE_DATE DATE,
  SERVER_INTERFACE VARCHAR(45),
  SERVER_AVERAGE_LIFE VARCHAR(45),
  SERVER_RPM VARCHAR(45),
  SERVER_DATARECOVERY_LIFE VARCHAR(45)
);
-- ETCSPEC
CREATE TABLE ETCSPEC (
	SPEC_NUM INT AUTO_INCREMENT PRIMARY KEY, -- 자동 증가 인덱스
    ETC_MFG VARCHAR(255),        -- 제조사
    ETC_SPEC_WARRANTY DATE,       -- 보증 기간 (날짜 형식)
    ETC_PURCHASE_DATE DATE,      -- 구매 일자 (날짜 형식)
    ETC_PRICE VARCHAR(45)    -- 가격
);

-- Category ------------------------------------------------------------------------
-- GROUP_CATEGORY
CREATE TABLE GROUP_CATEGORY (
  CATEGORY_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(30),
  CATEGORY_PARENT_NUM INT
);

-- IMG --------------------------------------------------------------------------
-- ITPRODIMG
CREATE TABLE ITPRODIMG (
  ITPRODIMG_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ASSETS_NUM INT,
  CATEGORY_NUM INT,
  ITPRODIMG_NAME VARCHAR(30),
  ITPRODIMG_UUID VARCHAR(100),
  ITPRODIMG_PATH VARCHAR(50),
  ITPRODIMG_REGDATE DATE,
  ITPROD_NUM INT
);
-- NOTICEIMG
CREATE TABLE NOTICEIMG (
  NOTICEIMG_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOTICE_NUM2 INT,
  NOTICEIMG_NAME VARCHAR(30),
  NOTICEIMG_UUID VARCHAR(100),
  NOTICEIMG_PATH VARCHAR(4096),
  NOTICEIMG_REGDATE DATE
);

-- etc --------------------------------------------------------------------------
-- NOTICE
CREATE TABLE NOTICE (
  NOTICE_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOTICE_NAME VARCHAR(30) NOT NULL,
  NOTICE_TITLE VARCHAR(30) NOT NULL,
  NOTICE_CONTENT VARCHAR(3000) NOT NULL,
  NOTICE_REGDATE TIMESTAMP NOT NULL,
  NOTICE_ENDDATE TIMESTAMP NOT NULL,
  NOTICE_HITS INT
);
-- STOCK_APPROVAL
CREATE TABLE STOCK_APPROVAL (
  APPRO_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30),
  ASSETS_NUM INT,
  CATEGORY_NUM INT,
  APPRO_TITLE VARCHAR(50),
  APPRO_DATE TIMESTAMP,
  APPRO_COMMENT VARCHAR(3000),
  APPRO_KIND VARCHAR(10),
  APPRO_YN VARCHAR(10),
  APPRO_OKDATE TIMESTAMP,
  USERQ_NUM INT
);
-- STOCK_RETURN
CREATE TABLE STOCK_RETURN (
  RETURN_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ASSETS_NUM INT NOT NULL,
  username VARCHAR(30) NOT NULL,
  RETURN_KIND VARCHAR(30) NOT NULL,
  RETURN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  RETURN_TITLE VARCHAR(100) NOT NULL,
  RETURN_COMMENT VARCHAR(1000),
  RETURN_STATUS VARCHAR(30) DEFAULT '승인대기',
  RETURN_ASSETS_DETAIL_NAME VARCHAR(30)
);
-- USER
CREATE TABLE USER (
  username VARCHAR(30) NOT NULL PRIMARY KEY,
  password VARCHAR(60),
  USER_NAME VARCHAR(30),
  USER_EMAIL VARCHAR(30),
  USER_DEPART VARCHAR(30),
  USER_PHONE VARCHAR(30),
  USER_ADDRESS VARCHAR(50),
  role VARCHAR(20),
  USER_JOINDATE TIMESTAMP,
  USER_LEAVE_YN VARCHAR(1) DEFAULT 'N',
  USER_LEAVEDATE TIMESTAMP
);
-- USER_REQUEST
CREATE TABLE USER_REQUEST (
  USERQ_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  CATEGORY_NUM INT NOT NULL,
  ASSETS_NUM INT NOT NULL,
  USERQ_TITLE VARCHAR(30) NOT NULL,
  USERQ_COUNT INT NOT NULL,
  USERQ_REGDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  USERQ_KIND VARCHAR(10) NOT NULL,
  USERQ_COMMENT VARCHAR(500) NOT NULL,
  USERQ_YN VARCHAR(20) NOT NULL DEFAULT '사원요청',
  USERQ_GRANTOR VARCHAR(30),
  USERQ_OKDATE TIMESTAMP
);


-- 테이블 삭제 후보
-- ASSETS_RECORD
CREATE TABLE ASSETS_RECORD (
  RECORD_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NUM INT,
  ASSETS_NUM INT,
  USER_ID INT
);
-- categories
CREATE TABLE categories (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30),
  parent_id INT
);



